# Generated by Django 4.1.3 on 2023-08-04 06:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Skill",
            new_name="Skills",
        ),
    ]
