# Generated by Django 4.1.3 on 2023-08-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_rename_skills_skill"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=100)),
                ("school", models.CharField(max_length=100)),
            ],
        ),
    ]
