# Generated by Django 4.1.3 on 2023-08-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_education"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("description1", models.CharField(blank=True, max_length=200)),
                ("description2", models.CharField(blank=True, max_length=200)),
                ("description3", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
