# Generated by Django 4.1.3 on 2023-08-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experience",
            name="place",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="experience",
            name="year",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
