# Generated by Django 4.1.3 on 2023-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_alter_experience_place_alter_experience_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="description1",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="description2",
        ),
        migrations.RemoveField(
            model_name="experience",
            name="description3",
        ),
        migrations.AddField(
            model_name="experience",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="experience",
            name="place",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="experience",
            name="year",
            field=models.CharField(max_length=100),
        ),
    ]
