# Generated by Django 4.1.3 on 2023-08-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_remove_experience_description1_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="description",
        ),
        migrations.AddField(
            model_name="experience",
            name="description1",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="experience",
            name="description2",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="experience",
            name="description3",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="experience",
            name="place",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="experience",
            name="year",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
