# Generated by Django 4.1.3 on 2023-08-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0009_portfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolio",
            name="category",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_URL",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="project_date",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="portfolio",
            name="image",
            field=models.ImageField(upload_to="portfolio"),
        ),
    ]
