# Generated by Django 4.1.3 on 2023-08-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0012_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_name", models.CharField(max_length=30)),
                ("service_img", models.ImageField(upload_to="portfolio")),
                ("service_icon", models.CharField(max_length=25)),
                ("service_desc", models.TextField()),
            ],
        ),
    ]
