# Generated by Django 4.1.3 on 2023-08-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0013_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("about1", models.TextField()),
                ("about2", models.TextField()),
                ("one_liner", models.CharField(max_length=200)),
                ("career", models.CharField(max_length=100)),
                ("dob", models.DateField()),
                ("age", models.IntegerField()),
                ("degree", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("freelance", models.CharField(max_length=50)),
                ("image", models.ImageField(upload_to="portfolio")),
                ("location", models.CharField(max_length=100)),
                ("quote", models.CharField(max_length=200)),
            ],
        ),
    ]
