# Generated by Django 4.1.3 on 2023-08-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0015_about_bgimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="bgimage",
            field=models.ImageField(upload_to="portfolio"),
        ),
    ]
