# Generated by Django 4.1.3 on 2023-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0016_alter_about_bgimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="about",
            name="apple_icon",
            field=models.ImageField(default="", upload_to="portfolio"),
        ),
        migrations.AddField(
            model_name="about",
            name="favicon",
            field=models.ImageField(default="", upload_to="portfolio"),
        ),
        migrations.AddField(
            model_name="about",
            name="i_am",
            field=models.CharField(default="", max_length=100),
        ),
    ]
