# Generated by Django 4.1.3 on 2023-08-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0017_about_apple_icon_about_favicon_about_i_am"),
    ]

    operations = [
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedin", models.URLField()),
                ("whatsapp", models.URLField()),
                ("instagram", models.URLField()),
                ("github", models.URLField()),
                ("twitter", models.URLField()),
            ],
        ),
    ]
