# Generated by Django 4.1.3 on 2023-08-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0018_social"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfolio",
            name="project_URL",
            field=models.CharField(default="", max_length=200),
        ),
    ]
