# Generated by Django 4.1.3 on 2023-08-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0019_alter_portfolio_project_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="portfolio",
            name="image",
        ),
        migrations.AddField(
            model_name="portfolio",
            name="image1",
            field=models.ImageField(blank=True, upload_to="portfolio"),
        ),
        migrations.AddField(
            model_name="portfolio",
            name="logo_image",
            field=models.ImageField(blank=True, upload_to="portfolio"),
        ),
    ]
