# Generated by Django 4.2.4 on 2024-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0021_about_meta_desc_about_meta_href_about_meta_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skill",
            name="proficiency",
        ),
        migrations.AddField(
            model_name="skill",
            name="skill_img",
            field=models.ImageField(blank=True, upload_to="portfolio"),
        ),
    ]
