# Generated by Django 4.2.4 on 2024-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0022_remove_skill_proficiency_skill_skill_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="skill_img",
            field=models.FileField(blank=True, upload_to="portfolio"),
        ),
    ]
