# Generated by Django 4.2.4 on 2024-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0023_alter_skill_skill_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="clink",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="experience",
            name="cname",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
